% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\usepackage{ctex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={地理建模实验4 实验报告},
  pdfauthor={42109232 \quad 吕文博 \quad 地信2101班},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{地理建模实验4 实验报告}
\author{42109232 \quad 吕文博 \quad 地信2101班}
\date{2024-05-23}

\begin{document}
\maketitle

\section{\texorpdfstring{\texttt{R}
语言多元线性回归}{R 语言多元线性回归}}\label{r-ux8bedux8a00ux591aux5143ux7ebfux6027ux56deux5f52}

\subsubsection{加载数据}\label{ux52a0ux8f7dux6570ux636e}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dt }\OtherTok{=}\NormalTok{ readxl}\SpecialCharTok{::}\FunctionTok{read\_xlsx}\NormalTok{(}\StringTok{\textquotesingle{}../data/exp4/4.xlsx\textquotesingle{}}\NormalTok{)}
\NormalTok{skimr}\SpecialCharTok{::}\FunctionTok{skim}\NormalTok{(dt)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule\noalign{}
\endfirsthead
\endhead
\bottomrule\noalign{}
\endlastfoot
Name & dt \\
Number of rows & 52 \\
Number of columns & 4 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
character & 1 \\
numeric & 3 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\end{longtable}

\textbf{Variable type: character}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1944}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1389}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1944}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0556}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0556}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.0833}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1250}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 14\tabcolsep) * \real{0.1528}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_missing
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
complete\_rate
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
max
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
empty
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
n\_unique
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
whitespace
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
台站 & 0 & 1 & 2 & 5 & 0 & 52 & 0 \\
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.1923}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0769}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0673}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0673}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0769}}
  >{\raggedleft\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.0769}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 20\tabcolsep) * \real{0.2577}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
skim\_variable
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
mean
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
sd
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p25
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p50
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p75
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
hist
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
年降水量P/mm & 372.20 & 215.17 & 159.01 & 420.52 & 542.56 & ▆▃▅▇▂ \\
纬度坐标Y（北纬0°） & 36.75 & 2.38 & 34.93 & 35.79 & 38.80 & ▅▇▃▅▃ \\
海拔Z/m & 1756.98 & 608.32 & 1343.00 & 1560.90 & 2036.92 & ▇▇▃▁▁
\end{longtable}

\subsubsection{拟合多元线性回归模型}\label{ux62dfux5408ux591aux5143ux7ebfux6027ux56deux5f52ux6a21ux578b}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm.model }\OtherTok{=} \FunctionTok{lm}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{年降水量P/mm}\StringTok{\textasciigrave{}} \SpecialCharTok{\textasciitilde{}} \StringTok{\textasciigrave{}}\AttributeTok{纬度坐标Y（北纬0°）}\StringTok{\textasciigrave{}} \SpecialCharTok{+} \StringTok{\textasciigrave{}}\AttributeTok{海拔Z/m}\StringTok{\textasciigrave{}}\NormalTok{,}
              \AttributeTok{data =}\NormalTok{ dt)}
\FunctionTok{summary}\NormalTok{(lm.model)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = `年降水量P/mm` ~ `纬度坐标Y（北纬0°）` + 
##     `海拔Z/m`, data = dt)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -188.63  -57.85  -12.86   40.47  178.58 
## 
## Coefficients:
##                         Estimate Std. Error t value Pr(>|t|)    
## (Intercept)           3260.83143  200.51255  16.262   <2e-16 ***
## `纬度坐标Y（北纬0°）`  -80.62259    5.24426 -15.373   <2e-16 ***
## `海拔Z/m`                0.04235    0.02055   2.061   0.0446 *  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 88.68 on 49 degrees of freedom
## Multiple R-squared:  0.8368, Adjusted R-squared:  0.8301 
## F-statistic: 125.6 on 2 and 49 DF,  p-value: < 2.2e-16
\end{verbatim}

\emph{R方为0.8368,说明数据有83.68\%的可能被该回归方程解释,数据与模型的拟合程度较高.}

\emph{由回归方程的F检验可得,\(P < 2.2e-16 << 0.05\),
F检验通过,说明回归方程显著,自变量能显著影响因变量.}

\emph{回归模型的方程为
\(\text{年降水量} = -80.62259 \times \text{纬度坐标} + 0.04235 \times \text{海拔} + 3260.83143\)
,对自变量进行t检验,\(P_{\text{纬度坐标}} < 2e-16 << 0.05\)且\(P_{\text{海拔}} = 0.0446 < 0.05\),纬度坐标和海拔的t检验都通过,说明两个自变量能显著影响因变量.}

\section{\texorpdfstring{\texttt{Python}
多元线性回归}{Python 多元线性回归}}\label{python-ux591aux5143ux7ebfux6027ux56deux5f52}

\begin{Shaded}
\begin{Highlighting}[]
\ImportTok{import}\NormalTok{ numpy }\ImportTok{as}\NormalTok{ np}
\ImportTok{import}\NormalTok{ pandas }\ImportTok{as}\NormalTok{ pd}
\ImportTok{import}\NormalTok{ statsmodels.api }\ImportTok{as}\NormalTok{ sm}
\ImportTok{import}\NormalTok{ matplotlib.pyplot }\ImportTok{as}\NormalTok{ plt}

\NormalTok{dt }\OperatorTok{=}\NormalTok{ pd.read\_excel(}\StringTok{\textquotesingle{}../data/exp4/4.xlsx\textquotesingle{}}\NormalTok{)}
\NormalTok{dt.head()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    台站  年降水量P/mm  纬度坐标Y（北纬0°）   海拔Z/m
## 0  安西     48.25    40.500000  1170.8
## 1  白银    193.72    36.599998  1707.2
## 2  定西    413.94    35.533000  1908.8
## 3  古浪    358.60    37.483003  2072.4
## 4  和政    615.04    35.432998  2136.4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X }\OperatorTok{=}\NormalTok{ dt.loc[:,[}\StringTok{\textquotesingle{}纬度坐标Y（北纬0°）\textquotesingle{}}\NormalTok{,}\StringTok{\textquotesingle{}海拔Z/m\textquotesingle{}}\NormalTok{]]}
\NormalTok{y }\OperatorTok{=}\NormalTok{ dt.loc[:,}\StringTok{\textquotesingle{}年降水量P/mm\textquotesingle{}}\NormalTok{]}
\NormalTok{X }\OperatorTok{=}\NormalTok{ sm.add\_constant (X)}
\NormalTok{lm\_model }\OperatorTok{=}\NormalTok{ sm.OLS(y,X).fit()}
\BuiltInTok{print}\NormalTok{(lm\_model.summary())}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                             OLS Regression Results                            
## ==============================================================================
## Dep. Variable:               年降水量P/mm   R-squared:                       0.837
## Model:                            OLS   Adj. R-squared:                  0.830
## Method:                 Least Squares   F-statistic:                     125.6
## Date:                  周四, 23 5月 2024   Prob (F-statistic):           5.16e-20
## Time:                        15:06:23   Log-Likelihood:                -305.46
## No. Observations:                  52   AIC:                             616.9
## Df Residuals:                      49   BIC:                             622.8
## Df Model:                           2                                         
## Covariance Type:            nonrobust                                         
## ===============================================================================
##                   coef    std err          t      P>|t|      [0.025      0.975]
## -------------------------------------------------------------------------------
## const        3260.8314    200.513     16.262      0.000    2857.886    3663.776
## 纬度坐标Y（北纬0°）   -80.6226      5.244    -15.373      0.000     -91.161     -70.084
## 海拔Z/m           0.0424      0.021      2.061      0.045       0.001       0.084
## ==============================================================================
## Omnibus:                        1.609   Durbin-Watson:                   1.438
## Prob(Omnibus):                  0.447   Jarque-Bera (JB):                1.588
## Skew:                           0.358   Prob(JB):                        0.452
## Kurtosis:                       2.530   Cond. No.                     3.03e+04
## ==============================================================================
## 
## Notes:
## [1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
## [2] The condition number is large, 3.03e+04. This might indicate that there are
## strong multicollinearity or other numerical problems.
\end{verbatim}

\emph{R方为0.837,说明数据有83.7\%的可能被该回归方程解释,数据与模型的拟合程度较高.}

\emph{由回归方程的F检验可得,\(P = 5.16e-20 << 0.05\),
F检验通过,说明回归方程显著,自变量能显著影响因变量.}

\emph{回归模型的方程为
\(\text{年降水量} = -80.6226 \times \text{纬度坐标} + 0.0424 \times \text{海拔} + 3260.8314\)
,对自变量进行t检验,\(P_{\text{纬度坐标}} = 0 << 0.05\)且\(P_{\text{海拔}} = 0.045 < 0.05\),纬度坐标和海拔的t检验都通过,说明两个自变量能显著影响因变量.}

\end{document}
